# terratorch-configs/classification_eurosat.yaml

task: classification

data:
  dataset: geobench.eurosat_rgb     # Example GEO-Bench dataset key
  split: standard                   # Use library-provided split
  batch_size: 64
  num_workers: 4

model:
  backbone: prithvi-100m           # Example backbone identifier
  pretrained: true
  head: linear                      # Linear classifier head
  num_classes: 10                   # EuroSAT RGB has 10 classes

trainer:
  max_epochs: 5
  precision: 16
  accelerator: auto

optim:
  name: adamw
  lr: 3.0e-4
  weight_decay: 0.01

outputs:
  dir: runs/classification_eurosat