name: geoAI
channels:
  - conda-forge
  - pytorch
dependencies:
  # Python version
  - python=3.11

  # Core scientific computing
  - numpy<2  # Using numpy 1.x for compatibility
  - pandas>=2.0
  - scipy>=1.14
  - matplotlib>=3.10
  - seaborn>=0.13

  # PyTorch ecosystem (Mac GPU support via MPS)
  - pytorch>=2.2
  - torchvision>=0.17
  - torchaudio>=2.2

  # Machine learning
  - scikit-learn>=1.7
  - joblib>=1.5

  # HuggingFace ecosystem
  - transformers>=4.55
  - datasets>=3.6
  - huggingface_hub>=0.34
  - accelerate>=1.9
  - tokenizers>=0.21
  - safetensors>=0.5

  # Geospatial core libraries
  - gdal>=3.10
  - rasterio>=1.4
  - fiona>=1.10
  - geopandas>=1.1
  - shapely>=2.1
  - pyproj>=3.7
  - xarray>=2025.7
  - netcdf4>=1.6
  - rioxarray>=0.15

  # Geospatial visualization
  - folium>=0.20
  - cartopy>=0.22

  # Earth observation
  - earthengine-api>=1.6
  - pystac-client>=0.7

  # Deep learning for geospatial
  - torchgeo>=0.7
  - pytorch-lightning>=2.5
  - lightning>=2.5
  - timm>=1.0
  - kornia>=0.8
  - einops>=0.8

  # Computer vision
  - opencv>=4.8
  - pillow>=11.3

  # Jupyter ecosystem
  - jupyter>=1.1
  - jupyterlab>=4.4
  - ipykernel>=6.30
  - ipywidgets>=8.1
  - notebook>=7.4
  - nbformat>=5.10
  - nbclient>=0.10

  # Data processing utilities
  - tqdm>=4.67
  - click>=8.2
  - pyyaml>=6.0
  - fsspec>=2025.3
  - requests>=2.32
  - aiohttp>=3.12

  # Scientific data formats
  - h5py>=3.11
  - zarr>=2.18
  - blosc>=1.21

  # Development and utilities
  - cryptography>=45.0
  - packaging>=25.0
  - typing_extensions>=4.14

  # Code quality and pre-commit tools
  - pre-commit>=4.0
  - black>=24.0
  - isort>=5.13
  - flake8>=7.0
  - mypy>=1.13
  - bandit>=1.7
  - pydocstyle>=6.3

  # Statistical and ML utilities
  - statsmodels>=0.14

  # Additional ML libraries via pip
  - pip>=24.0
  - pip:
    - panflute>=2.3.1
    - segmentation-models-pytorch>=0.5.0
    - efficientnet-pytorch>=0.7.1
    - lightly>=1.5.22
    - pretrainedmodels>=0.7.4
    - torchmetrics>=1.8.0

    # Specialized geospatial tools
    - pyogrio>=0.11.0
    - mapclassify>=2.10.0
    - rtree>=1.4.0
    - contextily>=1.6.0
    - planetary-computer>=1.0.0
    - stackstac>=0.5.0
    - rich>=13.7.1

    # Hydra for configuration management
    - hydra-core>=1.3.2
    - omegaconf>=2.3.0

    # Additional utilities
    - validators>=0.35.0
    - munch>=4.0.0
    - cachetools>=5.5.2
    
    # Course tooling
    - terratorch
    - geobench