name: geoAI
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyviz
  - defaults

dependencies:
  # Core Python
  - python=3.11
  
  # CUDA and GPU acceleration
  - cudatoolkit=11.8
  - cudnn=8.9
  - nccl
  
  # PyTorch ecosystem (GPU optimized)
  - pytorch=2.1.*
  - torchvision=0.16.*
  - torchaudio=2.1.*
  - pytorch-cuda=11.8
  - pytorch-lightning=2.1.*
  - torchmetrics
  - tensorboard
  - tensorboardx
  
  # Scientific computing (GPU-accelerated where available)
  - numpy=1.24.*
  - scipy=1.11.*
  - pandas=2.1.*
  - scikit-learn=1.3.*
  - scikit-image=0.21.*
  - matplotlib=3.7.*
  - seaborn=0.12.*
  - plotly=5.17.*
  - bokeh=3.3.*
  
  # Geospatial core libraries
  - gdal=3.7.*
  - rasterio=1.3.*
  - fiona=1.9.*
  - shapely=2.0.*
  - geopandas=0.14.*
  - pyproj=3.6.*
  - cartopy=0.22.*
  - contextily=1.4.*
  
  # Multi-dimensional data analysis
  - xarray=2023.10.*
  - zarr=2.16.*
  - netcdf4=1.6.*
  - h5py=3.10.*
  - dask=2023.10.*
  - distributed=2023.10.*
  
  # Earth observation and remote sensing
  - earthengine-api=0.1.*
  - satpy=0.44.*
  - pyresample=1.27.*
  - rioxarray=0.15.*
  
  # Computer vision and image processing
  - opencv=4.8.*
  - pillow=10.0.*
  - imageio=2.31.*
  - tifffile=2023.9.*
  
  # Jupyter and interactive computing
  - jupyter=1.0.*
  - jupyterlab=4.0.*
  - ipykernel=6.25.*
  - ipywidgets=8.1.*
  - notebook=7.0.*
  - nbconvert=7.9.*
  
  # Visualization and dashboards
  - folium=0.15.*
  - holoviews=1.18.*
  - panel=1.3.*
  - datashader=0.16.*
  - geoviews=1.11.*
  
  # Performance and optimization
  - numba=0.58.*
  - cython=3.0.*
  - joblib=1.3.*
  - tqdm=4.66.*
  - psutil=5.9.*
  
  # Development and utilities
  - git=2.42.*
  - black=23.9.*
  - flake8=6.1.*
  - pytest=7.4.*
  - pre-commit=3.5.*
  - click=8.1.*
  - pyyaml=6.0.*
  - toml=0.10.*
  - requests=2.31.*
  - aiohttp=3.8.*
  - httpx=0.25.*
  
  # File handling and data formats
  - fsspec=2023.10.*
  - s3fs=2023.10.*
  - gcsfs=2023.10.*
  - adlfs=2023.9.*
  
  # Pip packages that are not available via conda
  - pip=23.3.*
  - pip:
    # Geospatial ML specialized libraries
    - torchgeo==0.5.*
    - segmentation-models-pytorch==0.3.*
    - albumentations==1.3.*
    - rasterio[s3]==1.3.*
    - terratorch
    - geobench
    
    # Foundation models and transformers
    - transformers==4.35.*
    - datasets==2.14.*
    - huggingface-hub==0.19.*
    - accelerate==0.24.*
    - peft==0.6.*
    - bitsandbytes==0.41.*
    - sentence-transformers==2.2.*
    
    # Geospatial specific ML tools
    - geemap==0.28.*
    - ee-extra==0.0.*
    - geetools==1.3.*
    - eemont==0.3.*
    - wxee==0.4.*
    
    # API and web frameworks
    - fastapi==0.104.*
    - uvicorn[standard]==0.24.*
    - streamlit==1.28.*
    - gradio==3.50.*
    - dash==2.14.*
    - flask==3.0.*
    
    # MLOps and experiment tracking
    - mlflow==2.8.*
    - wandb==0.16.*
    - neptune-client==1.8.*
    - comet-ml==3.35.*
    - tensorstore==0.1.*
    
    # Additional computer vision
    - timm==0.9.*
    - efficientnet-pytorch==0.7.*
    - segmentation-models==1.0.*
    
    # Distributed computing extensions
    - ray[default]==2.8.*
    - modin[ray]==0.24.*
    - cudf-cu11==23.10.*  # GPU-accelerated pandas alternative
    - cupy-cuda11x==12.3.*  # GPU-accelerated numpy
    
    # Advanced geospatial analysis
    - leafmap==0.25.*
    - pystac==1.8.*
    - pystac-client==0.7.*
    - planetary-computer==1.0.*
    - stackstac==0.4.*
    - odc-stac==0.3.*
    
    # Satellite-specific tools
    - landsatxplore==0.15.*
    - sentinelsat==1.2.*
    - sentinelhub==3.9.*
    - planet==2.4.*
    
    # Climate and meteorological data
    - xesmf==0.8.*
    - cf-xarray==0.8.*
    - metpy==1.5.*
    - wrf-python==1.3.*
    
    # Authentication and cloud services
    - google-auth==2.23.*
    - google-cloud-storage==2.10.*
    - boto3==1.29.*
    - azure-storage-blob==12.19.*
    
    # Optimization and hyperparameter tuning
    - optuna==3.4.*
    - hyperopt==0.2.*
    - ray[tune]==2.8.*
    
    # Additional utilities
    - rich==13.7.*
    - typer==0.9.*
    - loguru==0.7.*
    - omegaconf==2.3.*
    - hydra-core==1.3.*
    
    # Notebook extensions and widgets
    - ipyleaflet==0.17.*
    - ipympl==0.9.*
    - ipyvolume==0.6.*
    - pythreejs==2.4.*
    
    # Model serving and deployment
    - bentoml==1.1.*
    - torchserve==0.8.*
    - tritonclient[http]==2.38.*
    
    # Advanced visualization
    - deck-gl==0.8.*
    - pydeck==0.8.*
    - keplergl==0.3.*
    - plotly-express==0.4.*